//
// Created by jens on 07-06-21.
//

#ifndef SIMPLESATSOLVER_SRC_PUMPKIN_PROPAGATORS_DYNAMIC_PAIRS_PROPAGATOR_PB_PAIRS_H_
#define SIMPLESATSOLVER_SRC_PUMPKIN_PROPAGATORS_DYNAMIC_PAIRS_PROPAGATOR_PB_PAIRS_H_

namespace Pumpkin {
class PropagatorPbPairs {};
}
#endif // SIMPLESATSOLVER_SRC_PUMPKIN_PROPAGATORS_DYNAMIC_PAIRS_PROPAGATOR_PB_PAIRS_H_
