//
// Created by jens on 07-06-21.
//

#ifndef SIMPLESATSOLVER_SRC_PUMPKIN_PROPAGATORS_DYNAMIC_PAIRS_WATCHED_PB_PAIRS_CONSTRAINT_H_
#define SIMPLESATSOLVER_SRC_PUMPKIN_PROPAGATORS_DYNAMIC_PAIRS_WATCHED_PB_PAIRS_CONSTRAINT_H_

namespace Pumpkin {
class WatchedPbPairsConstraint : public WatchedDynamicConstraint {

};
}
#endif // SIMPLESATSOLVER_SRC_PUMPKIN_PROPAGATORS_DYNAMIC_PAIRS_WATCHED_PB_PAIRS_CONSTRAINT_H_
